import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import type { CtxharnessConfig } from './config.js'
import { runExtractor } from './extractors/index.js'
import { runScanner, STANDALONE_SCANNERS } from './scanners/index.js'
import type { ScanResult } from './scanners/index.js'
import fg from 'fast-glob'

// ─── Generated-file detection ─────────────────────────────────────────────────

const GENERATED_PATTERNS = [
  /generated/i,
  /@generated/,
  /DO NOT EDIT/i,
  /auto-generated/i,
]

/**
 * Detects if a file is generated by checking its first 5 lines for generation markers,
 * or by checking if it matches an entry in the generatedFrom config map.
 * Returns the source path hint if generated, null otherwise.
 */
export function detectGeneratedFile(
  filePath: string,
  generatedFrom?: Record<string, string>,
): string | null {
  // Check generatedFrom config
  if (generatedFrom) {
    for (const [fragment, sourcePath] of Object.entries(generatedFrom)) {
      if (filePath.includes(fragment)) {
        return sourcePath
      }
    }
  }

  // Check first 5 lines of file for generation markers
  try {
    const content = readFileSync(filePath, 'utf-8')
    const lines = content.split('\n').slice(0, 5)
    for (const line of lines) {
      for (const pattern of GENERATED_PATTERNS) {
        if (pattern.test(line)) {
          return filePath
        }
      }
    }
  } catch {
    // File not readable — skip
  }

  return null
}

export type AssertionResult = {
  id: string
  label: string
  expected: string | null
  error: string | null
  results: ScanResult[]
  status: 'pass' | 'fail' | 'error' | 'no-mention' | 'skip' | 'warn'
}

export type RunResult = {
  assertions: AssertionResult[]
  totalPass: number
  totalFail: number
  totalWarn: number
  totalError: number
  totalSkip: number
  durationMs: number
}

export async function run(config: CtxharnessConfig, root: string): Promise<RunResult> {
  const t0 = performance.now()

  // 1. Collect files to scan via glob
  const files = await fg(config.files.include, {
    cwd: root,
    ignore: config.files.exclude,
    absolute: true,
    onlyFiles: true,
  })

  // 2. Process each assertion
  const assertions: AssertionResult[] = config.assertions.map((assertion) => {
    let expected: string | null = null
    let error: string | null = null
    let results: ScanResult[] = []

    // Run extractor to get the ground-truth value
    try {
      expected = runExtractor(assertion.extractor, root, assertion.extractorArgs ?? {})
    } catch (e) {
      error = e instanceof Error ? e.message : String(e)
      return {
        id: assertion.id,
        label: assertion.label ?? assertion.id,
        expected: null,
        error,
        results: [],
        status: 'error',
      }
    }

    // Merge assertion-level valueAllowlist into scannerArgs for coverageRatio.
    // For freshnessScore, inject _sourceFile from extractorArgs.path for display.
    const mergedScannerArgs = { ...(assertion.scannerArgs ?? {}) }
    if (assertion.valueAllowlist && assertion.valueAllowlist.length > 0) {
      const existing = (mergedScannerArgs['valueAllowlist'] as string[] | undefined) ?? []
      mergedScannerArgs['valueAllowlist'] = [...existing, ...assertion.valueAllowlist]
    }
    if (assertion.scanner === 'freshnessScore' && typeof assertion.extractorArgs?.['path'] === 'string') {
      mergedScannerArgs['_sourceFile'] = resolve(root, assertion.extractorArgs['path'] as string)
    }

    const isStandalone = STANDALONE_SCANNERS.has(assertion.scanner)

    if (isStandalone) {
      // Run once with root — scanner resolves its own targets
      try {
        results = runScanner(assertion.scanner, root, expected, mergedScannerArgs)
      } catch (e) {
        error = e instanceof Error ? e.message : String(e)
        return { id: assertion.id, label: assertion.label ?? assertion.id, expected, error, results: [], status: 'error' }
      }
    } else {
      // Determine the file set: per-assertion scopeFiles takes priority over global files
      const scanFiles = assertion.scopeFiles
        ? fg.sync(assertion.scopeFiles.include ?? config.files.include, {
            cwd: root,
            ignore: assertion.scopeFiles.exclude ?? config.files.exclude,
            absolute: true,
            onlyFiles: true,
          })
        : files

      // Run the scanner on every matched file
      for (const filePath of scanFiles) {
        try {
          let fileResults = runScanner(
            assertion.scanner,
            filePath,
            expected,
            mergedScannerArgs,
          )

          // Annotate generated-file results with a note pointing to the source
          const genSource = detectGeneratedFile(filePath, config.files.generatedFrom)
          if (genSource) {
            fileResults = fileResults.map((r) =>
              r.status === 'fail' ? { ...r, note: `generated file — fix in: ${genSource}` } : r,
            )
          }

          results = results.concat(fileResults)
        } catch {
          // Scanner error on one file — record as a fail result and continue
          results.push({
            file: filePath,
            line: 0,
            actual: '',
            expected,
            status: 'fail',
          })
        }
      }
    }

    // Apply allowlist: mark fail results from allowlisted files as 'skip'
    if (assertion.allowlist && assertion.allowlist.length > 0) {
      results = results.map((r) => {
        if (r.status !== 'fail') return r
        const isAllowlisted = assertion.allowlist!.some(
          (pattern) => r.file.endsWith(pattern) || r.file.includes(pattern),
        )
        return isAllowlisted ? { ...r, status: 'skip' as const } : r
      })
    }

    // Determine overall status for this assertion:
    //   - 'fail'       if any (non-allowlisted) result has status === 'fail'
    //   - 'warn'       if any result has status === 'warn' (and none is 'fail')
    //   - 'skip'       if fails existed but all were allowlisted (no real pass either)
    //   - 'no-mention' if nothing was found anywhere (no matches at all)
    //   - 'pass'       otherwise
    const hasFail = results.some((r) => r.status === 'fail')
    const hasWarn = results.some((r) => r.status === 'warn')
    const hasSkip = results.some((r) => r.status === 'skip')
    const hasMentions = results.some((r) => r.actual !== '' || r.status === 'pass' || r.status === 'warn')

    let status: AssertionResult['status']
    if (hasFail) {
      status = 'fail'
    } else if (hasWarn) {
      status = 'warn'
    } else if (hasMentions) {
      status = 'pass'
    } else if (hasSkip) {
      status = 'skip'
    } else {
      status = 'no-mention'
    }

    return {
      id: assertion.id,
      label: assertion.label ?? assertion.id,
      expected,
      error: null,
      results,
      status,
    }
  })

  const durationMs = performance.now() - t0
  const totalPass = assertions.filter((a) => a.status === 'pass').length
  const totalFail = assertions.filter((a) => a.status === 'fail').length
  const totalWarn = assertions.filter((a) => a.status === 'warn').length
  const totalError = assertions.filter((a) => a.status === 'error').length
  const totalSkip = assertions.filter((a) => a.status === 'skip').length

  return { assertions, totalPass, totalFail, totalWarn, totalError, totalSkip, durationMs }
}
